version: '2'

services:
  debian-build:
    image: dalibo/pgtsq-sdk:stretch
    volumes:
    - ..:/workspace/pg-track-slow-queries-src
    command: /workspace/pg-track-slow-queries-src/packaging/docker_make_deb.sh
