version: '2'

services:
  debian-stretch-build:
    image: dalibo/pgtsq-sdk:stretch
    volumes:
    - ..:/workspace/pg-track-slow-queries-src
    command: /workspace/pg-track-slow-queries-src/packaging/docker_make_deb.sh
    user: ${CURRENT_UID}

  debian-buster-build:
    image: dalibo/pgtsq-sdk:buster
    volumes:
    - ..:/workspace/pg-track-slow-queries-src
    command: /workspace/pg-track-slow-queries-src/packaging/docker_make_deb.sh
    user: ${CURRENT_UID}

  alpine-build:
    image: postgres:11-alpine
    volumes:
    - ..:/workspace/pg-track-slow-queries-src
    command: /workspace/pg-track-slow-queries-src/packaging/docker_make_apk.sh

